{% set version = "2.5.7.22" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-psychtools
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/psychTools_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/psychTools/psychTools_{{ version }}.tar.gz
  sha256: adfab961a8743d91cba9d2b29f7ad774758c26e8dfe3bc4739165c6dd650bfb1

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-foreign
    - r-psych
    - r-rtf
  run:
    - r-base
    - r-foreign
    - r-psych
    - r-rtf

test:
  commands:
    - $R -e "library('psychTools')"           # [not win]
    - "\"%R%\" -e \"library('psychTools')\""  # [win]

about:
  home: https://personality-project.org/r/psych/ https://personality-project.org/r/psych-manual.pdf
  license: GPL-2.0-or-later
  summary: Support functions,  data sets, and vignettes for the 'psych' package. Contains several of the biggest data sets for the 'psych' package as well as one vignette. A few helper functions for file manipulation are included as well. For more information, see the <https://personality-project.org/r/> web page.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - izahn
